### ISSUE TITLE
Stagetimer.io module 

### ISSUE THREAD

**Issue by nacalai** [bitfocus/companion-module-hermann-stagetimerio#1]
An API was just released for stagetimer.io. which is a web based timer which has a lot of neat features. Having an own module for it would be very neat for those of us who are not too experienced or not wanting to fiddle around too much with setting it up manually with the  generic module.

https://stagetimer.io/docs/api/

Thanks!

**Comment by josephdadams** [comment]
Done, transferred this issue to that repo

**Comment by estilles** [comment]
Thanks @josephdadams!

**Comment by nacalai** [comment]
Great! Feel free to keep me updated :) I haven't dug to deep into the apis, but I wonder if it's possible to output timer and/or text from variables. That would be nice.

**Comment by estilles** [comment]
> Great! Feel free to keep me updated :) I haven't dug to deep into the apis, but I wonder if it's possible to output timer and/or text from variables. That would be nice.

As of today, using the API we can:

- Start/Stop timers (using the ROOM_ID and TIMER_INDEX)
- Tweak timer (i.e. add/subtract time to current timer in a ROOM_ID)
- Flash current timer (in a ROOM_ID)
- Blackout current timer (in a ROOM_ID)
- Set which is the current timer (in a given ROOM_ID)
- Show/Hide messages (using the ROOM_ID and message INDEX)

That's it. That's all the API provides right now. The actions I will create in the module will be based on this.

As you can see, the API doesn't return any state. I'm not entirely sure what you mean by "output timer and/or text from variables", but if you mean the module should provide variables that contain the current time/text of a timer, then there's no way of doing that at this time.

**Comment by estilles** [comment]
@nacalai ... you can follow the progress of the module [here](https://github.com/bitfocus/companion-module-hermann-stagetimerio/projects/1).

**Comment by estilles** [comment]
@nacalai ... initial version of the module has been released. It's already available in the latest beta build.

**Comment by lhermann** [comment]
@estilles @nacalai creator of stagetimer.io here. Sorry for reviving this thread 😅

Currently the API does not return values. Internally we use web sockets. How could we make values like message text or current time available as variables in Companion?

**Comment by estilles** [comment]
> @estilles @nacalai creator of stagetimer.io here. Sorry for reviving this thread 😅
>
> Currently the API does not return values. Internally we use web sockets. How could we make values like message text or current time available as variables in Companion?

Hey Lukas! We spoke briefly via email a few weeks ago. I've been meaning to send you and Liz a message regarding adding feedbacks and variables to the module.

There're many ways to tackle this, but since you're already using web sockets internally, that might be the way to go. I guess my questions are:

- Do you have the web sockets API documented?
- Does is use any sort of authentication (like Room ID and API Key)?

If the answers to these questions are yes, then we can definitely use web sockets to add feedbacks and variables to the module.

This is a separate topic though. We should probably create a separate issue.

**Comment by kgfox1** [comment]
I am enjoying the API and using Companion to control the timers without a dedicated PC.  One thing I was hoping for was a way to show which timer was active (I believe you are currently working on that).  As a workaround, I have setup button actions as follows.  This requires the creation of a customer variable that I have called Timer On:

- Timer 1
-      Press Actions
-           stagetimer:Timer:Set - Timer Index (0)
-           internal: Set custom variable value - (Timer On)(1)
-      Feedback
-           internal: Check variable value - (Timer On)(=)(1)
-           Change style properties - (Color)(Background)

- Timer 2
-      Press Actions
-           stagetimer:Timer:Set - Timer Index (1)
-           internal: Set custom variable value - (Timer On)(2)
-      Feedback
-           internal: Check variable value - (Timer On)(=)(2)
-           Change style properties - (Color)(Background)


This works to highlight whichever Timer is currently active.
